<?php

namespace AppBundle\Repository;

/**
 * GalleryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryItemRepository extends \Doctrine\ORM\EntityRepository
{
}
