app_gallery_item:
    resource: "@AppBundle/Controller/GalleryItemController.php"
    type:     annotation

app_gallery_item:
    resource: "@AppBundle/Controller/GalleryItemController.php"
    type:     annotation

app_gallery:
    resource: "@AppBundle/Controller/GalleryController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
